local Instance = import("../Instance")
local typeof = import("../functions/typeof")

describe("instances.GuiObject", function()
	it("should instantiate", function()
		local instance = Instance.new("GuiObject")

		assert.not_nil(instance)
	end)

	it("should have properties defined", function()
		local instance = Instance.new("GuiObject")
		assert(typeof(instance.Active), "boolean")
		assert(typeof(instance.AnchorPoint), "Vector2")
		assert(typeof(instance.AutoButtonColor), "boolean")
		assert(typeof(instance.BackgroundColor3), "Color3")
		assert(typeof(instance.BackgroundTransparency), "number")
		assert(typeof(instance.BorderSizePixel), "number")
		assert(typeof(instance.ClipsDescendants), "boolean")
		assert(typeof(instance.Frame), "UDim2")
		assert(typeof(instance.InputBegan), "Signal")
		assert(typeof(instance.InputEnded), "Signal")
		assert(typeof(instance.LayoutOrder), "number")
		assert(typeof(instance.Position), "UDim2")
		assert(typeof(instance.Size), "UDim2")
		assert(typeof(instance.Visible), "boolean")
	end)
end)
