local Instance = import("../Instance")
local typeof = import("../functions/typeof")
local ZIndexBehavior = import("../Enum/ZIndexBehavior")

describe("instances.ScreenGui", function()
	it("should instantiate", function()
		local instance = Instance.new("ScreenGui")

		assert.not_nil(instance)
	end)

	it("should have properties defined", function()
		local instance = Instance.new("ScreenGui")
		assert.equals(typeof(instance.AbsolutePosition), "Vector2")
		assert.equals(typeof(instance.ZIndexBehavior), "EnumItem")
		assert.equals(instance.ZIndexBehavior.EnumType, ZIndexBehavior)
	end)

	describe("DisplayOrder", function()
		it("should return a number", function()
			local instance = Instance.new("ScreenGui")
			assert.equals(type(instance.DisplayOrder), "number")
		end)
	end)

	describe("AbsoluteSize", function()
		it("should return a Vector2", function()
			local instance = Instance.new("ScreenGui")
			assert.equals(typeof(instance.AbsoluteSize), "Vector2")
		end)
	end)

	describe("AutoLocalize", function()
		it("should return a boolean", function()
			local instance = Instance.new("ScreenGui")
			assert.equals(type(instance.AutoLocalize), "boolean")
		end)
	end)

	describe("IgnoreGuiInset", function()
		it("should return a boolean", function()
			local instance = Instance.new("ScreenGui")
			assert.equals(type(instance.IgnoreGuiInset), "boolean")
		end)
	end)
end)