local createEnum = import("../createEnum")

return createEnum("Font", {
	Legacy = 0,
	Arial = 1,
	ArialBold = 2,
	SourceSans = 3,
	SourceSansBold = 4,
	SourceSansSemibold = 16,
	SourceSansLight = 5,
	SourceSansItalic = 6,
	Bodoni = 7,
	Garamond = 8,
	Cartoon = 9,
	Code = 10,
	Highway = 11,
	SciFi = 12,
	Arcade = 13,
	Fantasy = 14,
	Antique = 15,
	Gotham = 17,
	GothamSemibold = 18,
	GothamBold = 19,
	GothamBlack = 20,
})
